"""macOS launchd integration — the durable ("permanent") schedule on macOS,
driven from the same UI button as the Windows path.

launchd is macOS's service/scheduler manager. A per-user scheduled job is a
*LaunchAgent*: a .plist in ~/Library/LaunchAgents that launchd auto-loads at
login. Like the Windows Interactive task, a LaunchAgent runs while the user is
logged on (running while fully logged off would need a root LaunchDaemon in
/Library/LaunchDaemons — admin/sudo).

We generate a wrapper .sh holding the run config (incl. the URI), chmod 600 it,
and a plist that runs it daily via StartCalendarInterval. launchd has no random
delay, so jitter is applied as a short random sleep inside run_window.py
(LOADGEN_JITTER_MAX_SEC). The N-day range is honoured by having the wrapper
self-remove (launchctl bootout) once past its end date.
"""
from __future__ import annotations

import os
import platform
import subprocess
from datetime import timedelta

import config
from db import redact_uri
from logbus import BUS
from tz import now_utc

IS_MAC = platform.system() == "Darwin"

BASE = os.path.dirname(os.path.abspath(__file__))
MAC_DIR = os.path.join(BASE, "mac_tasks")
LABEL = "com.loadgen.daily"
PLIST_PATH = os.path.expanduser(f"~/Library/LaunchAgents/{LABEL}.plist")
PYTHON = os.path.join(BASE, "venv", "bin", "python")
RUN_WINDOW = os.path.join(BASE, "run_window.py")


def _sh(args: list[str]) -> tuple[int, str]:
    proc = subprocess.run(args, capture_output=True, text=True)
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def _write_wrapper(cfg: dict, end_epoch: int, jitter_sec: int) -> str:
    os.makedirs(MAC_DIR, exist_ok=True)
    path = os.path.join(MAC_DIR, "loadgen-daily.sh")
    uri = cfg["uri"]
    auth = cfg.get("auth_source") or ""
    db = cfg.get("default_db") or config.DEFAULT_DB
    out = cfg.get("output_dir") or os.path.join(BASE, "runs")
    duration = int(cfg.get("duration_seconds", 600))
    base_seed = int(cfg.get("base_seed", 1234))
    blend_threads = int(cfg.get("blend_threads", 12))
    lines = [
        "#!/bin/bash",
        "# Generated by loadgen UI (permanent schedule, macOS launchd).",
        "# Contains the connection URI incl. password -> chmod 600. Regenerated each schedule.",
        f"END_EPOCH={end_epoch}",
        'if [ "$(date +%s)" -ge "$END_EPOCH" ]; then',
        f'  launchctl bootout gui/$(id -u)/{LABEL} 2>/dev/null',
        f'  rm -f "{PLIST_PATH}"',
        "  exit 0",
        "fi",
        f'export LOADGEN_URI="{uri}"',
    ]
    if auth:
        lines.append(f'export LOADGEN_AUTH_SOURCE="{auth}"')
    lines += [
        f'export LOADGEN_DB="{db}"',
        f'export LOADGEN_OUTPUT_DIR="{out}"',
        f'export LOADGEN_DURATION={duration}',
        f'export LOADGEN_BASE_SEED={base_seed}',
        f'export LOADGEN_BLEND_THREADS={blend_threads}',
        'export LOADGEN_AUTO_SEED=1',
        f'export LOADGEN_SEED_LARGE={int(cfg.get("seed_large", config.SMOKE_SEED_LARGE_COUNT))}',
        f'export LOADGEN_SEED_AGG={int(cfg.get("seed_agg", 50000))}',
        f'export LOADGEN_SEED_HOT={int(cfg.get("seed_hot", config.DEFAULT_HOT_DOCS))}',
        f'export LOADGEN_JITTER_MAX_SEC={jitter_sec}',
        f'cd "{BASE}"',
        f'"{PYTHON}" "{RUN_WINDOW}"',
        "",
    ]
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    os.chmod(path, 0o600)
    return path


def _write_plist(wrapper: str, hour: int, minute: int) -> str:
    os.makedirs(os.path.dirname(PLIST_PATH), exist_ok=True)
    log = os.path.join(BASE, "runs", "launchd-loadgen.log")
    plist = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>{LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>{wrapper}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key><integer>{hour}</integer>
    <key>Minute</key><integer>{minute}</integer>
  </dict>
  <key>RunAtLoad</key><false/>
  <key>StandardOutPath</key><string>{log}</string>
  <key>StandardErrorPath</key><string>{log}</string>
</dict>
</plist>
"""
    with open(PLIST_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(plist)
    return PLIST_PATH


def create_persistent_task(cfg: dict) -> dict:
    """Register (or replace) the launchd LaunchAgent. Never raises."""
    if not IS_MAC:
        return {"ok": False, "task_name": LABEL,
                "error": "macOS launchd scheduling is only available on macOS."}
    start_ist = cfg.get("start_ist", config.DEFAULT_WINDOW_START_IST)
    days = int(cfg.get("days", config.DEFAULT_SCHEDULE_DAYS))
    delay_min = int(cfg.get("random_delay_min", 15))
    try:
        hour, minute = (int(x) for x in start_ist.split(":"))
    except Exception:
        hour, minute = 10, 0
    end_epoch = int((now_utc() + timedelta(days=days)).timestamp())
    jitter_sec = max(0, delay_min * 60)

    wrapper = _write_wrapper(cfg, end_epoch, jitter_sec)
    plist = _write_plist(wrapper, hour, minute)
    BUS.info(f"mactask: registering launchd '{LABEL}' at {hour:02d}:{minute:02d} local, "
             f"{days}d, jitter<= {delay_min}m -> {redact_uri(cfg['uri'])}")

    uid = os.getuid()  # macOS only
    # Replace any existing instance, then bootstrap the new one.
    _sh(["launchctl", "bootout", f"gui/{uid}/{LABEL}"])
    rc, out = _sh(["launchctl", "bootstrap", f"gui/{uid}", plist])
    if rc != 0:
        # Fall back to the legacy load API on older macOS.
        rc, out = _sh(["launchctl", "load", "-w", plist])
    if rc != 0:
        return {"ok": False, "task_name": LABEL, "error": out.strip() or f"launchctl rc={rc}"}

    BUS.info(f"mactask: loaded launchd agent '{LABEL}'")
    return {"ok": True, "task_name": LABEL, "next_run": f"daily {hour:02d}:{minute:02d} local",
            "plist_path": plist, "wrapper_path": wrapper, "start_ist": start_ist, "days": days,
            "random_delay_min": delay_min,
            "note": "launchd LaunchAgent. Runs when you are logged on (survives reboot via "
                    "auto-load at login). Self-removes after the end date. "
                    "Verify: launchctl print gui/$(id -u)/" + LABEL}


def list_persistent_tasks() -> dict:
    if not IS_MAC:
        return {"tasks": [], "note": "macOS launchd scheduling is only available on macOS."}
    rc, out = _sh(["launchctl", "list"])
    loaded = any(LABEL in line for line in out.splitlines())
    tasks = []
    if loaded or os.path.exists(PLIST_PATH):
        tasks.append({"task_name": LABEL, "state": "Loaded" if loaded else "Plist present (not loaded)",
                      "next_run": "daily (see plist)", "last_run": "", "last_result": "",
                      "plist_path": PLIST_PATH})
    return {"tasks": tasks}


def remove_persistent_task(task_name: str = LABEL) -> dict:
    if not IS_MAC:
        return {"ok": False, "task_name": task_name,
                "detail": "macOS launchd scheduling is only available on macOS."}
    uid = os.getuid()
    _sh(["launchctl", "bootout", f"gui/{uid}/{LABEL}"])
    _sh(["launchctl", "unload", "-w", PLIST_PATH])  # legacy fallback, harmless if already out
    removed = []
    for p in (PLIST_PATH, os.path.join(MAC_DIR, "loadgen-daily.sh")):
        try:
            os.remove(p)
            removed.append(p)
        except OSError:
            pass
    BUS.info(f"mactask: removed launchd agent '{LABEL}'")
    return {"ok": True, "task_name": task_name, "detail": f"unloaded + removed {removed}"}
