"""Windows Task Scheduler integration — the durable ("permanent") schedule,
driven from the UI.

Unlike the in-app APScheduler (which only fires while the uvicorn process is
alive), a Windows scheduled task survives the app being closed and survives a
reboot. Because the app runs as a standard (non-elevated) user, the task is
registered with an Interactive logon: it runs when the operator is logged on
(it cannot run while fully logged off — that would need admin to register an
S4U/"run whether logged on or not" task).

We generate a wrapper .cmd holding the run config (incl. the URI), lock it down
with icacls, and register a daily task that runs run_window.py through it.
"""
from __future__ import annotations

import os
import platform
import subprocess

import config
from db import redact_uri
from logbus import BUS

IS_WINDOWS = platform.system() == "Windows"

_NON_WINDOWS_MSG = (
    "Permanent (Windows Task Scheduler) scheduling is only available on Windows. "
    "On macOS/Linux use the in-app schedule while the app runs, or the systemd timer "
    "(systemd/loadgen.timer) / a launchd plist / cron entry calling run_window.py — see README."
)

BASE = os.path.dirname(os.path.abspath(__file__))
WIN_DIR = os.path.join(BASE, "win_tasks")
TASK_NAME = "loadgen-daily"
PYTHON = os.path.join(BASE, "venv", "Scripts", "python.exe")
RUN_WINDOW = os.path.join(BASE, "run_window.py")


def _run_powershell(script: str) -> tuple[int, str]:
    proc = subprocess.run(
        ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", script],
        capture_output=True, text=True,
    )
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def _write_wrapper_cmd(cfg: dict) -> str:
    os.makedirs(WIN_DIR, exist_ok=True)
    cmd_path = os.path.join(WIN_DIR, f"{TASK_NAME}.cmd")
    uri = cfg["uri"]
    auth = cfg.get("auth_source") or ""
    db = cfg.get("default_db") or config.DEFAULT_DB
    out = cfg.get("output_dir") or os.path.join(BASE, "runs")
    duration = int(cfg.get("duration_seconds", 600))
    base_seed = int(cfg.get("base_seed", 1234))
    blend_threads = int(cfg.get("blend_threads", 12))
    lines = [
        "@echo off",
        "REM Generated by loadgen UI (permanent schedule). Contains the connection",
        "REM URI incl. password -> locked down with icacls. Regenerated on each schedule.",
        f'set "LOADGEN_URI={uri}"',
    ]
    if auth:
        lines.append(f'set "LOADGEN_AUTH_SOURCE={auth}"')
    lines += [
        f'set "LOADGEN_DB={db}"',
        f'set "LOADGEN_OUTPUT_DIR={out}"',
        f'set "LOADGEN_DURATION={duration}"',
        f'set "LOADGEN_BASE_SEED={base_seed}"',
        f'set "LOADGEN_BLEND_THREADS={blend_threads}"',
        'set "LOADGEN_AUTO_SEED=1"',
        f'set "LOADGEN_SEED_LARGE={int(cfg.get("seed_large", config.SMOKE_SEED_LARGE_COUNT))}"',
        f'set "LOADGEN_SEED_AGG={int(cfg.get("seed_agg", 50000))}"',
        f'set "LOADGEN_SEED_HOT={int(cfg.get("seed_hot", config.DEFAULT_HOT_DOCS))}"',
        f'cd /d "{BASE}"',
        f'"{PYTHON}" "{RUN_WINDOW}"',
        "",
    ]
    with open(cmd_path, "w", encoding="utf-8") as fh:
        fh.write("\r\n".join(lines))
    # Lock down: break inheritance, grant only this user + SYSTEM + Administrators.
    try:
        subprocess.run(["icacls", cmd_path, "/inheritance:r",
                        "/grant:r", f"{os.environ.get('USERNAME', 'Manis')}:F",
                        "/grant:r", "SYSTEM:F", "/grant:r", "Administrators:F"],
                       capture_output=True, text=True)
    except Exception as exc:  # noqa: BLE001
        BUS.warn(f"wintask: icacls lockdown failed (continuing): {exc}")
    return cmd_path


def create_persistent_task(cfg: dict) -> dict:
    """Register (or replace) the durable daily Windows task. Never raises."""
    if not IS_WINDOWS:
        return {"ok": False, "task_name": TASK_NAME, "error": _NON_WINDOWS_MSG}
    start_ist = cfg.get("start_ist", config.DEFAULT_WINDOW_START_IST)
    days = int(cfg.get("days", config.DEFAULT_SCHEDULE_DAYS))
    delay_min = int(cfg.get("random_delay_min", 15))
    duration = int(cfg.get("duration_seconds", 600))
    hours_limit = max(1, duration // 3600 + 1)

    cmd_path = _write_wrapper_cmd(cfg)
    BUS.info(f"wintask: registering '{TASK_NAME}' at {start_ist} (local=IST), "
             f"{days}d, +0..{delay_min}m jitter -> {redact_uri(cfg['uri'])}")

    # Build the PowerShell registration. cmd_path has no single quotes (it's a
    # filesystem path under the repo), so single-quote literals are safe here.
    ps = f"""
$ErrorActionPreference='Stop'
try {{
  $a = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument '/c "{cmd_path}"'
  $t = New-ScheduledTaskTrigger -Daily -At (Get-Date '{start_ist}')
  $t.RandomDelay = 'PT{delay_min}M'
  $t.EndBoundary = (Get-Date).AddDays({days}).ToString('s')
  $p = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive
  $s = New-ScheduledTaskSettingsSet -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Hours {hours_limit}) -MultipleInstances IgnoreNew
  Register-ScheduledTask -TaskName '{TASK_NAME}' -Action $a -Trigger $t -Principal $p -Settings $s -Force | Out-Null
  $i = Get-ScheduledTaskInfo -TaskName '{TASK_NAME}'
  Write-Output ('OK|' + $i.NextRunTime)
}} catch {{ Write-Output ('FAIL|' + $_.Exception.Message) }}
"""
    rc, out = _run_powershell(ps)
    out = out.strip()
    if "OK|" in out:
        next_run = out.split("OK|", 1)[1].strip()
        BUS.info(f"wintask: registered '{TASK_NAME}', next run {next_run or '(pending)'}")
        return {"ok": True, "task_name": TASK_NAME, "next_run": next_run,
                "cmd_path": cmd_path, "start_ist": start_ist, "days": days,
                "random_delay_min": delay_min,
                "note": "Runs when you are logged on (survives app close + reboot). "
                        "Cannot run while fully logged off."}
    return {"ok": False, "task_name": TASK_NAME, "error": out or f"powershell rc={rc}"}


def list_persistent_tasks() -> dict:
    if not IS_WINDOWS:
        return {"tasks": [], "note": _NON_WINDOWS_MSG}
    ps = (
        "$ts = Get-ScheduledTask | Where-Object {$_.TaskName -like 'loadgen*'};"
        "if(!$ts){Write-Output 'NONE'} else {"
        "foreach($x in $ts){$i=Get-ScheduledTaskInfo -TaskName $x.TaskName;"
        "Write-Output ($x.TaskName+'|'+$x.State+'|'+$i.NextRunTime+'|'+$i.LastRunTime+'|'+$i.LastTaskResult)}}"
    )
    rc, out = _run_powershell(ps)
    tasks = []
    for line in (out or "").splitlines():
        line = line.strip()
        if not line or line == "NONE" or "|" not in line:
            continue
        parts = line.split("|")
        tasks.append({
            "task_name": parts[0],
            "state": parts[1] if len(parts) > 1 else "",
            "next_run": parts[2] if len(parts) > 2 else "",
            "last_run": parts[3] if len(parts) > 3 else "",
            "last_result": parts[4] if len(parts) > 4 else "",
        })
    return {"tasks": tasks}


def remove_persistent_task(task_name: str = TASK_NAME) -> dict:
    if not IS_WINDOWS:
        return {"ok": False, "task_name": task_name, "detail": _NON_WINDOWS_MSG}
    ps = (f"try{{Unregister-ScheduledTask -TaskName '{task_name}' -Confirm:$false;"
          f"Write-Output 'OK'}}catch{{Write-Output ('FAIL|'+$_.Exception.Message)}}")
    rc, out = _run_powershell(ps)
    ok = "OK" in (out or "") and "FAIL" not in (out or "")
    if ok:
        BUS.info(f"wintask: removed task '{task_name}'")
        # Best-effort remove the wrapper (it holds the URI).
        try:
            os.remove(os.path.join(WIN_DIR, f"{task_name}.cmd"))
        except OSError:
            pass
    return {"ok": ok, "task_name": task_name, "detail": (out or "").strip()}
